// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: getBeef.proto

package getBeef

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBeefSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeefSummaryRequest) Reset() {
	*x = GetBeefSummaryRequest{}
	mi := &file_getBeef_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeefSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeefSummaryRequest) ProtoMessage() {}

func (x *GetBeefSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_getBeef_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeefSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetBeefSummaryRequest) Descriptor() ([]byte, []int) {
	return file_getBeef_proto_rawDescGZIP(), []int{0}
}

// Define a message for the top-level structure
type GetBeefSummaryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Beef          map[string]int64       `protobuf:"bytes,1,rep,name=beef,proto3" json:"beef,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Represents the "beef" map as a repeated field of BeefEntry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeefSummaryReply) Reset() {
	*x = GetBeefSummaryReply{}
	mi := &file_getBeef_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeefSummaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeefSummaryReply) ProtoMessage() {}

func (x *GetBeefSummaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_getBeef_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeefSummaryReply.ProtoReflect.Descriptor instead.
func (*GetBeefSummaryReply) Descriptor() ([]byte, []int) {
	return file_getBeef_proto_rawDescGZIP(), []int{1}
}

func (x *GetBeefSummaryReply) GetBeef() map[string]int64 {
	if x != nil {
		return x.Beef
	}
	return nil
}

var File_getBeef_proto protoreflect.FileDescriptor

var file_getBeef_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x65, 0x74, 0x42, 0x65, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x67, 0x65, 0x74, 0x42, 0x65, 0x65, 0x66, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x42,
	0x65, 0x65, 0x66, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x8a, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x65, 0x65, 0x66, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3a, 0x0a, 0x04, 0x62, 0x65, 0x65,
	0x66, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x67, 0x65, 0x74, 0x42, 0x65, 0x65,
	0x66, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x65, 0x66, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x42, 0x65, 0x65, 0x66, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x04, 0x62, 0x65, 0x65, 0x66, 0x1a, 0x37, 0x0a, 0x09, 0x42, 0x65, 0x65, 0x66, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x59,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x65, 0x65, 0x66, 0x12, 0x4e, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x42, 0x65, 0x65, 0x66, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1e, 0x2e, 0x67, 0x65,
	0x74, 0x42, 0x65, 0x65, 0x66, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x65, 0x66, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x65,
	0x74, 0x42, 0x65, 0x65, 0x66, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x65, 0x66, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x11, 0x5a, 0x0f, 0x67, 0x65, 0x74,
	0x42, 0x65, 0x65, 0x66, 0x2f, 0x67, 0x65, 0x74, 0x42, 0x65, 0x65, 0x66, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_getBeef_proto_rawDescOnce sync.Once
	file_getBeef_proto_rawDescData = file_getBeef_proto_rawDesc
)

func file_getBeef_proto_rawDescGZIP() []byte {
	file_getBeef_proto_rawDescOnce.Do(func() {
		file_getBeef_proto_rawDescData = protoimpl.X.CompressGZIP(file_getBeef_proto_rawDescData)
	})
	return file_getBeef_proto_rawDescData
}

var file_getBeef_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_getBeef_proto_goTypes = []any{
	(*GetBeefSummaryRequest)(nil), // 0: getBeef.GetBeefSummaryRequest
	(*GetBeefSummaryReply)(nil),   // 1: getBeef.GetBeefSummaryReply
	nil,                           // 2: getBeef.GetBeefSummaryReply.BeefEntry
}
var file_getBeef_proto_depIdxs = []int32{
	2, // 0: getBeef.GetBeefSummaryReply.beef:type_name -> getBeef.GetBeefSummaryReply.BeefEntry
	0, // 1: getBeef.GetBeef.GetBeefSummary:input_type -> getBeef.GetBeefSummaryRequest
	1, // 2: getBeef.GetBeef.GetBeefSummary:output_type -> getBeef.GetBeefSummaryReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_getBeef_proto_init() }
func file_getBeef_proto_init() {
	if File_getBeef_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_getBeef_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_getBeef_proto_goTypes,
		DependencyIndexes: file_getBeef_proto_depIdxs,
		MessageInfos:      file_getBeef_proto_msgTypes,
	}.Build()
	File_getBeef_proto = out.File
	file_getBeef_proto_rawDesc = nil
	file_getBeef_proto_goTypes = nil
	file_getBeef_proto_depIdxs = nil
}
