// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: getBeef.proto

package getBeef

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetBeef_GetBeefSummary_FullMethodName = "/getBeef.GetBeef/GetBeefSummary"
)

// GetBeefClient is the client API for GetBeef service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetBeefClient interface {
	GetBeefSummary(ctx context.Context, in *GetBeefSummaryRequest, opts ...grpc.CallOption) (*GetBeefSummaryReply, error)
}

type getBeefClient struct {
	cc grpc.ClientConnInterface
}

func NewGetBeefClient(cc grpc.ClientConnInterface) GetBeefClient {
	return &getBeefClient{cc}
}

func (c *getBeefClient) GetBeefSummary(ctx context.Context, in *GetBeefSummaryRequest, opts ...grpc.CallOption) (*GetBeefSummaryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBeefSummaryReply)
	err := c.cc.Invoke(ctx, GetBeef_GetBeefSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetBeefServer is the server API for GetBeef service.
// All implementations must embed UnimplementedGetBeefServer
// for forward compatibility.
type GetBeefServer interface {
	GetBeefSummary(context.Context, *GetBeefSummaryRequest) (*GetBeefSummaryReply, error)
	mustEmbedUnimplementedGetBeefServer()
}

// UnimplementedGetBeefServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetBeefServer struct{}

func (UnimplementedGetBeefServer) GetBeefSummary(context.Context, *GetBeefSummaryRequest) (*GetBeefSummaryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBeefSummary not implemented")
}
func (UnimplementedGetBeefServer) mustEmbedUnimplementedGetBeefServer() {}
func (UnimplementedGetBeefServer) testEmbeddedByValue()                 {}

// UnsafeGetBeefServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetBeefServer will
// result in compilation errors.
type UnsafeGetBeefServer interface {
	mustEmbedUnimplementedGetBeefServer()
}

func RegisterGetBeefServer(s grpc.ServiceRegistrar, srv GetBeefServer) {
	// If the following call pancis, it indicates UnimplementedGetBeefServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetBeef_ServiceDesc, srv)
}

func _GetBeef_GetBeefSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBeefSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetBeefServer).GetBeefSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetBeef_GetBeefSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetBeefServer).GetBeefSummary(ctx, req.(*GetBeefSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetBeef_ServiceDesc is the grpc.ServiceDesc for GetBeef service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetBeef_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "getBeef.GetBeef",
	HandlerType: (*GetBeefServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBeefSummary",
			Handler:    _GetBeef_GetBeefSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "getBeef.proto",
}
